# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8eGpCKg1Yjy9SWAZrSiAeS9Acd9on81

# Machine Learning Model Lifecycle

## 1. Preprocessing + Exploratory Data Analysis + Feature Selection

* **Preprocessing:** This step involves cleaning and preparing the data for modeling. This may include removing missing values, dealing with outliers, and transforming the data into a format that is suitable for the machine learning algorithm.
* **Exploratory Data Analysis (EDA):** This step involves exploring the data to gain insights into the relationships between the features and the target variable. This can help to identify which features are important and which features may be correlated with each other.
* **Feature Selection:** This step involves selecting a subset of features that are most likely to be important for the machine learning model. This can help to improve the performance of the model and reduce the risk of overfitting.

## 2. Extract Input and Output

* **Input:** The input data is the data that the machine learning model will use to make predictions. This data may include features such as the customer's age, income, and purchase history.
* **Output:** The output of the machine learning model is the prediction that the model makes. This prediction may be a class label, such as "spam" or "not spam," or it may be a continuous value, such as the price of a house.

## 3. Scale the value

* **Scaling:** This step involves scaling the data so that all of the features have a similar range of values. This is important because machine learning algorithms often work better when the features are scaled.

## 4. Train Test Split

* **Train:** The training data is used to train the machine learning model. The model learns to make predictions by finding patterns in the training data.
* **Test:** The test data is used to evaluate the performance of the machine learning model. The model makes predictions on the test data and the predictions are compared to the actual values.

## 5. Train the model

* **Algorithm:** This is the machine learning algorithm that will be used to build the model. There are many different machine learning algorithms available, each with its own strengths and weaknesses.
* **Parameters:** The parameters of the machine learning algorithm are the settings that control how the algorithm works. The parameters can be tuned to improve the performance of the model.

## 6. Evaluate the model

* **Metrics:** There are many different metrics that can be used to evaluate the performance of a machine learning model. Some common metrics include accuracy, precision, recall, and F1 score.
* **Error analysis:** This step involves analyzing the errors that the model makes. This can help to identify areas where the model can be improved.

## 7. Deploy the model

* **Deployment:** Once the model is trained and evaluated, it can be deployed in production. This means that the model can be used to make predictions on new data.
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/placement.csv')

df.isnull().sum()

df.isna().any()

df.sample(5)

"""## 1.Preprocessing"""

df=df.iloc[:,1:]

df.sample(3)

"""##EDA- Explorartory Data Analysis"""

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

"""## 2. Extract Input and Output"""

X=df.iloc[:,:-1]

y=df.iloc[:,-1]

X.shape

y.shape

"""##Here, X.shape-> (99,2) which means X is a matrix
##Y.shape-> (99,) which means Y is a vector

## 4.Train Test split
"""

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33)

y_train

"""##3. Scaling the dependant values"""

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)
X_train

X_test=scaler.fit_transform(X_test)
X_test

"""##5. Train the model"""

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

model.fit(X_train,y_train)

y_pred=model.predict(X_test)
y_pred

y_test

"""##6.Evaluate the Model"""

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

"""## Ploting the Decision Boundary"""

from mlxtend.plotting import plot_decision_regions

# Plotting decision regions
plot_decision_regions(X_train, y_train.values, clf=model, legend=2)

"""##7.Deploy the model"""

import pickle

pickle.dump(model,open('model.pkl','wb'))

