# -*- coding: utf-8 -*-
"""KNN_Imputer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nquAAa-Ffe7N6diNi_-Fh5OAGU4F4lC9
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/Titanic-Dataset.csv')[['Age','Pclass','Fare','Survived']]

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df

df.isnull().mean()*100

X=df.drop(columns=['Survived'])
y=df['Survived']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

knn=KNNImputer(n_neighbors=5,weights='distance')

X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.fit_transform(X_test)

X_train_trf=pd.DataFrame(X_train_trf,columns=X_train.columns)
X_test_trf=pd.DataFrame(X_test_trf,columns=X_train.columns)

lr=LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred=lr.predict(X_test_trf)

accuracy_score(y_pred,y_test)

si=SimpleImputer()

X_train_trf2=si.fit_transform(X_train)

X_test_trf2=si.fit_transform(X_test)


X_train_trf2=pd.DataFrame(X_train_trf2,columns=X_train.columns)
X_test_trf2=pd.DataFrame(X_test_trf2,columns=X_train.columns)

lr=LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred=lr.predict(X_test_trf2)

accuracy_score(y_pred,y_test)

knn=KNNImputer(add_indicator=True)

X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.fit_transform(X_test)

lr=LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred=lr.predict(X_test_trf)

accuracy_score(y_pred,y_test)

knn=KNNImputer(n_neighbors=5,weights='uniform',add_indicator=True)

X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.fit_transform(X_test)

lr=LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred=lr.predict(X_test_trf)

accuracy_score(y_pred,y_test)

