# -*- coding: utf-8 -*-
"""Day4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W5-RoeStF1nZ0QbG0G3C7GfBc3inK9TC

#*Bivariate and Multivariate Data analysis*
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

tips=sns.load_dataset('tips')

tips.info()

tips.head()

titanic=pd.read_csv('/content/Titanic-Dataset.csv')

iris=sns.load_dataset('iris')

flights=sns.load_dataset('flights')

"""#*1.Scatterplot(Numerical-Numerical)*"""

plt.scatter(tips['total_bill'],tips['tip'])

sns.scatterplot(x=tips['total_bill'],y=tips['tip'], hue=tips['sex'])

sns.scatterplot(x=tips['total_bill'],y=tips['tip'], hue=tips['sex'],style=tips['smoker'])

sns.scatterplot(x=tips['total_bill'],y=tips['tip'], hue=tips['sex'],style=tips['smoker'],size=tips['size'])

color_paletee=["black","red"]

sns.scatterplot(
    x=tips['total_bill'],
    y=tips['tip'],
    hue=tips['sex'],
    style=tips['smoker'],
    palette=color_paletee
)

"""#*2.Bar plot(Numerical-Categorical)*"""

titanic.head()

sns.barplot(x=titanic['Pclass'],y=titanic['Fare'],hue=titanic['Sex'])

"""#*3.Boxplot(Numerical-Categorical)*"""

sns.boxplot(x=titanic['Sex'],y=titanic['Age'],hue=titanic['Survived'])

"""#*4.Dictplot(Numerical-Categorical)*"""

sns.distplot(titanic[titanic['Survived']==0]['Age'],hist=False)

sns.distplot(titanic[titanic['Survived']==1]['Age'],hist=False)

"""#*5.HeatMap->Categorical-Categorical*"""

pd.crosstab(titanic['Pclass'],titanic['Survived'])

sns.heatmap(pd.crosstab(titanic['Pclass'],titanic['Survived']))

(titanic.groupby('Pclass').mean()['Survived']*100).plot(kind='pie')

# Load Titanic dataset
titanic = sns.load_dataset('titanic')


# Calculate the mean of 'Survived' grouped by 'Sex'
(titanic.groupby('sex')['survived'].mean()*100).plot(kind='pie')

"""#*6.ClusterMap->Categorical-Categorical*"""

pd.crosstab(titanic['SibSp'],titanic['Survived'])

titanic.groupby('SibSp')['Survived'].mean()*100

sns.clustermap(pd.crosstab(titanic['SibSp'],titanic['Survived']))

sns.clustermap(pd.crosstab(titanic['Parch'],titanic['Survived']))

"""#*7.Pairplot->(Numerical Columns)*"""

sns.pairplot(tips)

sns.pairplot(iris,hue='species')

"""#*8.Lineplot->(Numerical Columns)*"""

flights.head(5)

new=flights.groupby('year').sum().reset_index()

new

sns.lineplot(x=new['year'],y=new['passengers'])

flights.pivot_table(values='passengers',index='month',columns='year')

sns.heatmap(flights.pivot_table(values='passengers',index='month',columns='year'))

sns.clustermap(flights.pivot_table(values='passengers',index='month',columns='year'))



