# -*- coding: utf-8 -*-
"""Day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U7Dm1PmCWjJsROAnyQUmc4JOkjrQsJq4

#Univariate Analysis
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/Titanic-Dataset.csv')

df.sample(5)

df.info()

"""#---------------------------------------------------------Categorical Data---------------------------------------------------------

#a.Countplot
"""

sns.countplot(data = df.reset_index(), x = df['Survived'])

sns.countplot(data=df.reset_index(),x=df['Pclass'])

df['Survived'].value_counts()

df['Survived'].value_counts().plot(kind='bar')

"""#b.Piechart"""

df['Pclass'].value_counts().plot(kind='pie',autopct='%.1f')

"""#---------------------------------------------------------Numerical Data---------------------------------------------------------

#a.Histogram-> It is used to understand the numerical data ditsribution
"""

plt.hist(df['Age'],bins=20)

"""#b.Distplot->Its is known as PDF or Probabilty Distribution Function shows probability of features"""

sns.distplot(df['Age'])

"""#c.Boxplot"""

sns.boxplot(df['Age'])

"""
   skew() value is 0 it means data is uniformly distributed if it is below zero it is left shifted and if it is
above zero it is right shifted
"""
df['Age'].skew()

