# -*- coding: utf-8 -*-
"""Pipeline.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YbDtwJQqULw5eXUNc8rKx-ek_hD1RmR6
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline,make_pipeline
from sklearn.feature_selection import SelectKBest,chi2
from sklearn.tree import DecisionTreeClassifier

df=pd.read_csv('/content/Titanic-Dataset.csv')

df.head()

df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Survived'])
,df['Survived'],random_state=42,test_size=0.33)

#impute tranformer

transformer1=ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embark',SimpleImputer(strategy='most_frequent'),[6])],remainder='passthrough')

"""# *Here we are giving column index because it will turn convenient* #"""

#Ohe transformer

transformer2=ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

#Scaling

transformer3=ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

# feature selecton

transformer4=SelectKBest(score_func=chi2,k=8)

# Decision Tree

transformer5= DecisionTreeClassifier()

"""pipe=Pipeline([
    ('tranforemer1',transformer1),
    ('tranforemer2',transformer2),
    ('tranforemer3',transformer3),
    ('tranforemer4',transformer4),
    ('tranforemer5',transformer5)
])"""

pipe=make_pipeline(transformer1,transformer2,transformer3,transformer4,transformer5)

pipe.fit(X_train,y_train)

y_pred=pipe.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy_score(y_pred,y_test)

