# -*- coding: utf-8 -*-
"""Ordinal Encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EGh2W3FGL-MvPe6eaemfPeNYDp-3QSVx
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/customer.csv')

df.sample()

df.isna().any()

df=df.iloc[:,2:]

df.head()

"""##Ordinal Encoding- Review,Education
##Label Encoder-Purchased
"""

from sklearn.model_selection import train_test_split
X_test,X_train,y_test,y_train=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2)

X_train

from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['UG','PG','School']])

oe.fit(X_train)

oe.categories_

X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

le.fit(y_train)

le.classes_

y_train=le.transform(y_train)
y_test=le.transform(y_test)

y_train

from sklearn.linear_model import LinearRegression

model=LinearRegression()

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

