# -*- coding: utf-8 -*-
"""LogisticRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lpPe_aUmH1OzZbjVhiXrvGZf4eW2hgV7

#Logistic Regression
"""

!pip install scikit-learn

import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer
df=load_breast_cancer()
df

dataset=pd.DataFrame(df['data'],columns=df['feature_names'])
print(dataset)

y=pd.DataFrame(df['target'],columns=['Target'])
y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.data, df.target, test_size=0.33)

params=[{'C':[1,5,10,25],'max_iter':[100,200,159]}]
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
LogisticRegressor=LogisticRegression(C=100,max_iter=100)
model=GridSearchCV(LogisticRegressor,params,scoring='f1',cv=5)
model.fit(X_train,y_train)

model.best_params_

model.best_score_

y_pred=model.predict(X_test)

y_pred

from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

confusion_matrix(y_test,y_pred)

accuracy_score(y_test,y_pred)

print(classification_report(y_test,y_pred))

