# -*- coding: utf-8 -*-
"""Outlier Detection and Removal using IQR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YmiDCmeVZr5E2HDZ6qCA1IBD_tDnKp4v
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/placement (1).csv')

df.isna().sum()

df.info()

import matplotlib.pyplot as plt
import seaborn as sns

df['placement_exam_marks'].describe()

df['placement_exam_marks'].skew()

sns.boxplot(df['placement_exam_marks'])

plt.figure(figsize=(14,4))
plt.subplot(1,2,1)
sns.distplot(df['cgpa'])

plt.subplot(1,2,2)
sns.distplot(df['placement_exam_marks'])

"""## *For Inter quantile based filtering we need to cal Q1 ,Q3, IQR then we will see data beside Q1-1.5*IQR and Q3+1.5*IQR these will be our lower and upper limits and will see data in this range itself* ##"""

Q1=df['placement_exam_marks'].quantile(0.25)
Q3=df['placement_exam_marks'].quantile(0.75)

IQR=Q3-Q1

lower_limit=Q1-1.5*IQR
upper_limit=Q3+1.5*IQR

print(f"LOWER_LIMIT: {lower_limit}")
print(f"UPPER_LIMIT: {upper_limit}")

"""# Outliers"""

df[df['placement_exam_marks']<lower_limit]

df[df['placement_exam_marks']>upper_limit]

"""#Triming"""

new_df= df[df['placement_exam_marks']< upper_limit ]

new_df

plt.figure(figsize=(14,4))
plt.subplot(2,2,1)
sns.distplot(df['placement_exam_marks'])

plt.subplot(2,2,2)
sns.boxplot(df['placement_exam_marks'])

plt.subplot(2,2,3)
sns.distplot(new_df['placement_exam_marks'])

plt.subplot(2,2,4)
sns.boxplot(new_df['placement_exam_marks'])

"""# Caping"""

new_df_=df.copy()

new_df_['placement_exam_marks']=np.where(df['placement_exam_marks']>upper_limit,
upper_limit,np.where(df['placement_exam_marks']<lower_limit,
                     lower_limit,
                     df['placement_exam_marks']
                     )
)

new_df_

plt.figure(figsize=(14,4))
plt.subplot(2,2,1)
sns.distplot(df['placement_exam_marks'])

plt.subplot(2,2,2)
sns.boxplot(df['placement_exam_marks'])

plt.subplot(2,2,3)
sns.distplot(new_df_['placement_exam_marks'])

plt.subplot(2,2,4)
sns.boxplot(new_df_['placement_exam_marks'])

