# -*- coding: utf-8 -*-
"""Day5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ijEMNq0mtVjmgDPwwN2cKESooT1Ofgs4
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/Diwali Sales Data.csv',encoding='latin-1')

df.head()

df.sample(5)

df['Product_ID'].value_counts()

df.info()

df=df.drop(['Status','unnamed1'],axis=1)

df.info()

df.isnull().sum()

df.duplicated()

df.describe()

df.corr()

df.shape

df.dropna(inplace=True)
df.shape

df.info()

"""#Amount should be converted in int"""

df['Amount']=df['Amount'].astype(int)

df.info()

"""#*#EDA*

##*Categorical->Gender,Marital_status,State,Zone,Occupation, Product_Category*
##*Numerical-> Orders, Amount*
"""

sns.pairplot(df)

"""## *a.Which gender purchase more?*##
## *b.And to which age group they belong?*##
## *c.Which products are broght most?*##
"""

df['Product_Category'].value_counts()

ax=sns.countplot(data=df,x=df['Gender'])

for bars in ax.containers:
  ax.bar_label(bars)

sales_gender=df.groupby(['Gender'],as_index=False)['Amount'].sum()
sales_gender

sns.barplot(x='Gender',y='Amount',data=sales_gender)

"""##*Observation1: Female have spent far more than men*"""

ax=sns.countplot(data=df,x=df['Age Group'],hue=df['Gender'])

for bars in ax.containers:
  ax.bar_label(bars)

sales_age_group=df.groupby(['Age Group'],as_index=False)['Amount'].sum()
sales_age_group

sns.barplot(x='Age Group',y='Amount',data=sales_age_group)

"""## *Observation2: 26-35 age group people have shopped the most and that to female* ##

#*State-> No of orders*
"""

sales_state=df.groupby(['State'],as_index=False)['Orders'].sum().sort_values(by='Orders',ascending=False).reset_index().head(10)

sales_state

sns.set(rc={'figure.figsize':(16,5)})
sns.barplot(x='State',y='Orders',data=sales_state)

"""#*State-> Amount*"""

sales_amt_state=df.groupby(['State'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False).head(10)

sales_amt_state

sns.set(rc={'figure.figsize':(15,6)})
sns.barplot(x='State',y='Amount',data=sales_amt_state)

"""##*Marital_Status*"""

sns.set(rc={'figure.figsize':(7,6)})
ax=sns.countplot(data=df,x='Marital_Status')

for bars in ax.containers:
  ax.bar_label(bars)

sales_Marital=df.groupby(['Marital_Status','Gender'],as_index=False)['Amount'].sum()
sales_Marital

sns.set(rc={'figure.figsize':(6,5)})
sns.barplot(data=sales_Marital,x='Marital_Status',y='Amount',hue='Gender')

df['Occupation'].value_counts()

obs=pd.crosstab(df['Product_Category'],df['Occupation'])

sns.heatmap(obs)

sns.clustermap(obs)

sns.set(rc={'figure.figsize':(16,5)})
ax=sns.countplot(data=df,x='Occupation')

for bars in ax.containers:
  ax.bar_label(bars)

sales_occupation=df.groupby(['Occupation','Gender'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

sales_occupation

sns.barplot(data=sales_occupation,x='Occupation',y='Amount',hue='Gender')

"""#*Product Category*"""

ax=sns.countplot(data=df,x='Product_Category')

for bars in ax.containers:
  ax.bar_label(bars)

sales_category=df.groupby(['Product_Category'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False).head(10)

sales_category

sns.barplot(data=sales_category,x='Product_Category',y='Amount')

"""## *CONCLUSION:26-35 age married women from UP,Maharastra and karnatake working in IT Sector,Healthcare and aviation have bought food ,clothing and electronis*"""

