# -*- coding: utf-8 -*-
"""OneHotEncoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IEM_1aaxrDGZYfmARSPSW4zPPhCWPihR
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/cars (1).csv')

df.sample(10)

df['brand'].nunique()

df['brand'].value_counts()

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.33)

X_train

y_train

"""#*K One Hot Encoding |using Pandas->get_dummies()*"""

pd.get_dummies(df,columns=['fuel','owner'])

pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

"""#*One Hot Encoding using sklearn*"""

from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

X_train_new=ohe.fit_transform(X_train[['fuel','owner']])
X_train_new

X_test_new=ohe.fit_transform(X_test[['fuel','owner']])
X_test_new.shape

np.hstack((X_train[['brand','km_driven']].values,X_train_new))

"""#*One Hot Encoding with Top Categories*"""

count=df['brand'].value_counts()

count

threshold=100

repl=count[count<=threshold].index

repl

pd.get_dummies(df['brand'].replace(repl,'uncommon'))

